version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: banana
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
