version: '3.8'

services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: banana
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
